title: snai.pe
tagline: ""
url: "https://snai.pe"

github: Snaipe

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
      permalink: /posts/:title

plugins:
  - jekyll-redirect-from

sass:
  sass_dir: css/
  style: :compressed

exclude: [.sass-cache, .git, README.md, CNAME]
